import base64
import io
import logging
from dataclasses import asdict
from datetime import date

import pandas as pd
from jinja2 import Environment, BaseLoader

from .metrics import BacktestMetrics

logger = logging.getLogger(__name__)

_REPORT_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Backtest Report — {{ strategy }}</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 24px; color: #222; }
    h1 { color: #2c3e50; }
    h2 { color: #34495e; border-bottom: 1px solid #ccc; padding-bottom: 4px; }
    table { border-collapse: collapse; width: 100%; margin: 16px 0; }
    th { background: #2c3e50; color: #fff; padding: 8px 12px; text-align: left; }
    td { padding: 8px 12px; border-bottom: 1px solid #e0e0e0; }
    tr:nth-child(even) td { background: #f7f9fb; }
    .positive { color: #27ae60; font-weight: bold; }
    .negative { color: #e74c3c; font-weight: bold; }
    .chart { margin: 16px 0; }
    .meta { color: #555; margin-bottom: 16px; }
  </style>
</head>
<body>
  <h1>Backtest Report — {{ strategy }}</h1>
  <p class="meta">
    <strong>Symbol:</strong> {{ symbol }} &nbsp;|&nbsp;
    <strong>Timeframe:</strong> {{ timeframe }} &nbsp;|&nbsp;
    <strong>Period:</strong> {{ start_date }} → {{ end_date }}
  </p>

  <h2>Performance Metrics</h2>
  <table>
    <tr><th>Metric</th><th>Value</th></tr>
    <tr><td>Total Return</td>
        <td class="{{ 'positive' if metrics.total_return >= 0 else 'negative' }}">
          {{ "%.2f"|format(metrics.total_return * 100) }}%</td></tr>
    <tr><td>Annualised Return</td>
        <td class="{{ 'positive' if metrics.annualized_return >= 0 else 'negative' }}">
          {{ "%.2f"|format(metrics.annualized_return * 100) }}%</td></tr>
    <tr><td>Sharpe Ratio</td><td>{{ "%.4f"|format(metrics.sharpe_ratio) }}</td></tr>
    <tr><td>Sortino Ratio</td><td>{{ "%.4f"|format(metrics.sortino_ratio) }}</td></tr>
    <tr><td>Max Drawdown</td>
        <td class="negative">{{ "%.2f"|format(metrics.max_drawdown * 100) }}%</td></tr>
    <tr><td>Max Drawdown Duration (bars)</td><td>{{ metrics.max_drawdown_duration }}</td></tr>
    <tr><td>Win Rate</td><td>{{ "%.2f"|format(metrics.win_rate * 100) }}%</td></tr>
    <tr><td>Profit Factor</td><td>{{ "%.4f"|format(metrics.profit_factor) }}</td></tr>
    <tr><td>Total Trades</td><td>{{ metrics.total_trades }}</td></tr>
    <tr><td>Avg Win</td><td>${{ "%.2f"|format(metrics.avg_win) }}</td></tr>
    <tr><td>Avg Loss</td><td>${{ "%.2f"|format(metrics.avg_loss) }}</td></tr>
    <tr><td>Largest Win</td><td>${{ "%.2f"|format(metrics.largest_win) }}</td></tr>
    <tr><td>Largest Loss</td><td>${{ "%.2f"|format(metrics.largest_loss) }}</td></tr>
    <tr><td>Expectancy per Trade</td><td>${{ "%.2f"|format(metrics.expectancy) }}</td></tr>
    <tr><td>Avg Trade Duration (h)</td><td>{{ "%.1f"|format(metrics.avg_trade_duration) }}</td></tr>
  </table>

  {% if equity_chart %}
  <h2>Equity Curve</h2>
  <div class="chart">
    <img src="data:image/png;base64,{{ equity_chart }}"
         style="width:100%;max-width:1100px;" alt="Equity Curve">
  </div>
  {% endif %}

  {% if drawdown_chart %}
  <h2>Drawdown</h2>
  <div class="chart">
    <img src="data:image/png;base64,{{ drawdown_chart }}"
         style="width:100%;max-width:1100px;" alt="Drawdown">
  </div>
  {% endif %}

  {% if trades %}
  <h2>Trade Log</h2>
  <table>
    <tr>
      <th>#</th><th>Side</th><th>Entry Time</th><th>Exit Time</th>
      <th>Entry Price</th><th>Exit Price</th><th>P&amp;L</th>
    </tr>
    {% for t in trades %}
    <tr>
      <td>{{ loop.index }}</td>
      <td>{{ t.side }}</td>
      <td>{{ t.entry_time }}</td>
      <td>{{ t.exit_time }}</td>
      <td>${{ "%.4f"|format(t.entry_price) }}</td>
      <td>${{ "%.4f"|format(t.exit_price) }}</td>
      <td class="{{ 'positive' if t.pnl >= 0 else 'negative' }}">
        ${{ "%.2f"|format(t.pnl) }}</td>
    </tr>
    {% endfor %}
  </table>
  {% endif %}

  <p style="color:#999;font-size:12px;margin-top:32px;">
    Generated by Tradie Backtesting Service
  </p>
</body>
</html>"""


class BacktestReportGenerator:
    """Generates HTML backtest reports with optional matplotlib charts."""

    def __init__(self) -> None:
        self._env = Environment(loader=BaseLoader())
        self._template = self._env.from_string(_REPORT_TEMPLATE)

    def generate(
        self,
        strategy: str,
        symbol: str,
        timeframe: str,
        start_date: date,
        end_date: date,
        metrics: BacktestMetrics,
        equity_curve: pd.Series,
        trades: pd.DataFrame,
    ) -> str:
        equity_chart = self._render_equity_chart(equity_curve)
        drawdown_chart = self._render_drawdown_chart(equity_curve)

        trade_records = trades.to_dict("records") if len(trades) > 0 else []

        return self._template.render(
            strategy=strategy,
            symbol=symbol,
            timeframe=timeframe,
            start_date=start_date,
            end_date=end_date,
            metrics=metrics,
            equity_chart=equity_chart,
            drawdown_chart=drawdown_chart,
            trades=trade_records,
        )

    def _render_equity_chart(self, equity_curve: pd.Series) -> str | None:
        return self._render_chart(equity_curve, "Equity Curve ($)", "#2c7be5")

    def _render_drawdown_chart(self, equity_curve: pd.Series) -> str | None:
        if equity_curve.empty:
            return None
        running_max = equity_curve.cummax()
        drawdown = (equity_curve - running_max) / running_max * 100.0
        return self._render_chart(drawdown, "Drawdown (%)", "#e74c3c", fill=True)

    def _render_chart(
        self, series: pd.Series, ylabel: str, color: str, fill: bool = False
    ) -> str | None:
        try:
            import matplotlib  # noqa: PLC0415

            matplotlib.use("Agg")
            import matplotlib.pyplot as plt  # noqa: PLC0415
        except ImportError:
            logger.warning("matplotlib not available; charts will be omitted from report")
            return None

        if series.empty:
            return None

        fig, ax = plt.subplots(figsize=(12, 4))
        ax.plot(series.index, series.values, color=color, linewidth=1.2)
        if fill:
            ax.fill_between(series.index, series.values, 0, alpha=0.25, color=color)
        ax.set_ylabel(ylabel)
        ax.grid(True, alpha=0.3)
        fig.tight_layout()

        buf = io.BytesIO()
        fig.savefig(buf, format="png", dpi=100)
        plt.close(fig)
        buf.seek(0)
        return base64.b64encode(buf.read()).decode("ascii")
